// generated by https://quicktype.io
export type ServerOffer = {
  id: string;
  title: string;
  type: string;
  price: number;
  city: ServerCity;
  location: ServerLocation;
  isFavorite: boolean;
  isPremium: boolean;
  rating: number;
  previewImage: string;
}

export type ServerOfferDetail = Omit<ServerOffer, 'previewImage'> & {
  description: string;
  bedrooms: number;
  goods: string[];
  host: {
    name: string;
    avatarUrl: string;
    isPro: boolean;
  };
  images: string[];
  maxAdults: number;
}

export type ServerCity = {
  name: string;
  location: ServerLocation;
}

export type ServerLocation = {
  latitude: number;
  longitude: number;
  zoom: number;
}


export type City = ServerCity &{
  slug: string;
}
